import yaml

dict_1 = {u'RLDASH.dash_password': 65, u'presto-credits.header-text': 1, u'presto-pergame-charge.enabled': 1,
          u'loyalty-rewards.header-image-path': 34, u'loyalty-rewards.sign-in-body-text': 34,
          u'loyalty-rewards.loyalty-program': 34, u'loyalty-rewards.loyalty-banner-button-user-signedin-text': 34,
          u'check-timeout': 1, u'payment-allow-pin': 71, u'resource-sync.syncer-launch-app': 47,
          u'server-mode-allow-modifier-multi-selection': 47, u'server-mode.order-modes.option-0.display-text': 47,
          u'brightness-percentage': 31, u'logging-configs.client-log-context-size': 1, u'call-server.enabled': 51,
          u'loyalty-rewards.signup-bill-screen-enabled': 34, u'show-video-ads': 1, u'survey.default-star': 1,
          u'payment-allow-debit': 71, u'back-office.send-session-id': 1, u'presto-pergame-charge.pergame-price': 1,
          u'gift-card.pin-required-gc-ranges': 1, u'server-mode-async-order-sending': 47,
          u'payment-request-maximum-http-attempts': 42, u'payment.pay-full-label': 1,
          u'loyalty.label-for-visit-frequency': 1, u'handheld-lock-screen-login-aloha': 47,
          u'server-mode.order-modes.enabled': 47, u'debugging.simulate-card-swipe': 1, u'gift-card.qr-allowed': 44,
          u'loyalty.sign-in-pos-id': 1, u'server-mode.hide-duplicate-button': 47,
          u'paywall-dynamically-configurable-enabled': 58, u'coupon.qr-scan-allowed': 59, u'server-swipe.all-digits': 1,
          u'resource-sync.use-apache-http': 1, u'back-office.ssl-hostname-check': 1,
          u'loyalty-rewards.bill-screen-loyalty-button-enabled': 34, u'logging-configs.client-logging-url': 1,
          u'games-page-2.home_promo_video_banner.gradient_enabled': 107, u'loyalty-rewards.loyalty-banner-image': 34,
          u'ratings-enabled': 1, u'heartbeat-interval': 1, u'loyalty-rewards.signup-home-screen-enabled': 34,
          u'loyalty-rewards.loyalty-progress-msg-sign-out': 34, u'posmon-api-version': 1,
          u'hide-items-not-from-update': 1, u'survey.default-star-label4': 1, u'gift-card.pin-is-enabled': 1,
          u'loyalty-rewards.loyalty-progress-msg-sign-in': 34,
          u'server-mode.table-map.table-with-open-check-other-server-color': 47, u'resource-sync.https': 1,
          u'loyalty.sub-header-text': 34, u'server-mode.order-modes.options': 47, u'payment-giftcard-enabled': 43,
          u'server-mode.leave-table-with-unsent-items': 47, u'presto-credits.confirm-credit-purchase': 1,
          u'http-connect-timeout-secs': 1,
          u'loyalty-rewards.loyalty-opt-tandc-screen-fields.loyalty-opt-tandc-screen-fields-label1': 34,
          u'show-slideshow-dots': 1, u'block-pay-activity': 35, u'loyalty-rewards.enabled': 34,
          u'touch-metrics-enabled': 1, u'payment-request-retry-interval-seconds': 42, u'loyalty.opt-for-sms': 1,
          u'loyalty-rewards.loyalty-signup-screen-order': 34, u'loyalty-rewards.loyalty-progress-msg-apply-reward': 34,
          u'loyalty-rewards.dismiss-loyalty-popup-prompt-from-prestoapp-inactivity': 34,
          u'volume-initial-percentage-a2': 1, u'server-mode.refresh-check-button': 47, u'is-split-evenly-enabled': 37,
          u'loyalty-rewards.loyalty-tandc-next-button-transition-text': 34, u'payment-pin-entry-text': 71,
          u'server-mode.send-selected-items': 47, u'presto-credits.packs': 1, u'loyalty.loyalty-program': 34,
          u'server-mode.send-order-confirmation': 47, u'validation-timeout-secs': 47, u'payment-gateway-server': 1,
          u'survey.default-star-label1': 1, u'loyalty-rewards.reward-branding-logo': 34,
          u'server-mode.restaurant-synchronization-service-polling-interval': 75,
          u'server-mode.server-mode-required-drink-minimum': 47, u'survey.star-question': 1,
          u'RLDASH.encrypted_dash_password': 65, u'payment-log-third-party-logs': 74, u'reorder.enabled': 48,
          u'demo-fixed-price-enabled': 1, u'back-office.port': 1,
          u'show-loyalty-popup-from-homescreen-on-slide-dismiss': 34, u'payment-company-code': 61,
          u'server-mode.fast-table-switch-prompt-table-number': 47, u'server-mode.hot-spots-enabled': 55,
          u'loyalty-rewards.loyalty-tandc-header-text': 34, u'loyalty-rewards.loyalty-banner-background-color': 34,
          u'debugging.fake-menu-update.items': 1, u'server-mode.seat-numbering-enabled': 47,
          u'back-office.max-retries': 42, u'server-mode.non-associated-modifiers': 47, u'server-mode.classic-mode': 47,
          u'server-mode.pos-menu-row-count': 47, u'presto-credits.enabled': 1,
          u'loyalty-rewards.signup-signin-background-image': 34, u'loyalty.signup-home-screen-enabled': 1,
          u'loyalty-rewards.loyalty-tandc-enabled': 34, u'back-office.SSL': 1, u'info-label': 1,
          u'loyalty-rewards.loyalty-opt-tandc-screen-fields.loyalty-opt-tandc-screen-fields-key1': 34,
          u'web-storage.retry-failed-metrics-interval': 1, u'hide-premium-content-tag': 1,
          u'loyalty-rewards.reward-not-selectable-text': 34, u'server-mode.fast-server-switch': 47,
          u'gift-card.server-required-gc-ranges': 1, u'logging-configs.root-log-level': 1,
          u'server-mode.app-lockout-timeout-secs': 47, u'premium-surveys': 53,
          u'loyalty-rewards.loyalty-opt-tandc-screen-fields-label1': 34,
          u'loyalty-rewards.reward-image-placeholder': 34, u'payment.samsung-pay-enabled': 1,
          u'loyalty-rewards.loyalty-opt-tandc-screen-fields.loyalty-opt-tandc-screen-fields-link1': 34,
          u'survey.question-op1': 1, u'enable-list-view': 1, u'RLDASH.encrypted_dash_user': 65,
          u'in-game-advertising-enabled': 1, u'show-unavailable-modifiers': 1,
          u'loyalty-rewards.loyalty-signup-age-minimum': 34, u'batch-mode-max-delay-secs': 1,
          u'loyalty-rewards.loyalty-tandc-link1-text': 34, u'alert-trigger.survey-alert-trigger': 39,
          u'survey.default-star-label3': 1, u'call-server.check-open-mandatory': 52, u'server-mode.enabled': 103,
          u'info-1-label': 1, u'coupon.enabled': 59, u'server-mode.show-server-mode-alerts': 47,
          u'simplified-modifiers-enabled': 1, u'server-mode.list-item-full-highlight': 47,
          u'loyalty-rewards.post-payment-loyalty-text': 34, u'flash-sale.enabled': 1,
          u'server-mode.show-tables-map': 47, u'premium-survey-version': 53, u'waiter-info.email-is-enabled': 1,
          u'play-shine-effect-enabled': 1, u'server-mode.server-mode-allow-modifier-multi-selection': 47,
          u'wifi.wifi-retry-enabled': 104, u'send-employee-message-negative-survey-response': 39,
          u'payment.tip-after-tax': 102, u'RLDASH.pos_request_timeout_sec': 65,
          u'presto-credits.dialog-header-text-start': 1, u'server-mode.seat-numbering-for-items-enabled': 47,
          u'call-server.flashing-period': 1, u'survey.default-question-op1': 1, u'server-mode.display-check-price': 47,
          u'survey.default-question-op2': 1, u'loyalty.termscond-path': 34, u'loyalty.label-for-visit-meal-type': 1,
          u'server-mode.server-mode-async-order-sending': 47, u'host-server-control-panel.coupon-button-enabled': 57,
          u'RLDASH.update_discount_cache_interval_secs': 65, u'loyalty.sign-up-phone-screen-headline': 34,
          u'loyalty-rewards.loyalty-signup-birthday-screen-fields-required': 34, u'flash-sale.items': 1,
          u'order-webservice-version': 1, u'alert-trigger.payment-start-alert': 39,
          u'payment.printed-receipt-enabled-additional-message': 38,
          u'loyalty-rewards.loyalty-banner-button-user-notsignedin-text': 34, u'touch-metrics-host-local-cert': 1,
          u'payment-should-default-to-credit': 105, u'logging-configs.client-log-post-enable': 1,
          u'host-server-control-panel.right-button-text': 32,
          u'loyalty-rewards.dismiss-loyalty-popup-prompt-from-prestoapp-home-screen': 34,
          u'coupon.manual-entry-allowed': 59, u'loyalty-rewards.reward-branding-logo-enabled': 34,
          u'kiosk.kiosk-app': 47, u'server-mode.table-map.swap-highlight-layer': 47, u'http-read-timeout-secs': 1,
          u'alert-trigger.alcoholic-order-sent': 39, u'payment-p12-path': 1, u'loyalty-rewards.loyalty-tandc-link1': 34,
          u'loyalty-rewards.loyalty-tandc-link2': 34, u'employee-message-system': 39,
          u'payment-application-priority-list': 71, u'survey.default-question': 1, u'arcade-popup-enabled': 1,
          u'hide-pay-tag': 1, u'server-mode.category-id-list': 56, u'hide-cart': 54,
          u'host-server-control-panel.left-button-text': 32, u'presto-toons-enabled': 1, u'debugging.show-item-id': 1,
          u'payment-cert-path': 61, u'table-number.type': 1, u'loyalty-rewards.card-swipe-default': 34,
          u'payment.printed-receipt-disabled-additional-message': 38, u'reorder.show-prices': 48,
          u'gift-card.manual-entry-allowed': 43, u'info-3-label': 1, u'loyalty-rewards.loyalty-tandc-text': 34,
          u'back-office.ssl-code-check': 1, u'XPIENT.orderpoint': 65, u'server-mode.validation-timeout-secs': 47,
          u'featured-content-slide-show-seconds': 1, u'loyalty.privacy-path': 1, u'loyalty.text-for-terms-link': 34,
          u'RLDASH.is_gift_card_enabled': 65, u'server-mode.table-map.table-with-open-check-color': 47,
          u'coupon.max-accepted': 59, u'show-server-mode-alerts': 47, u'loyalty.joined-perks': 1,
          u'play-scroll-effect-enabled': 1, u'loyalty-rewards.logo-image-path': 34,
          u'loyalty-rewards.loyalty-sms-tandc-enabled': 34, u'XPIENT.aarp_bin': 65, u'web-storage.url': 1,
          u'premium-content-enabled': 84, u'override-games-free': 1, u'loyalty-rewards.sign-in-title-text': 34,
          u'loyalty.text-for-privacy-link': 1, u'server-mode.menu-item-order-offset': 47, u'split-by-item.enabled': 36,
          u'loyalty.label-for-visiting-members': 1, u'loyalty-rewards.sign-up-body-text': 34,
          u'loyalty-rewards.show-loyalty-popup-from-homescreen-on-slide-dismiss': 34,
          u'server-mode.fast-table-switch': 47, u'loyalty.header-image-path': 1,
          u'loyalty.text-to-accept-loyalty-terms': 1, u'survey.word-question': 1, u'info-2-label': 1,
          u'menu-update-interval': 66, u'loyalty.background-image-path': 1, u'unlock-elc-model.pos-id': 40,
          u'split-by-item.disabled-on-partial-payment': 1, u'presto-credits.initial-balance': 1,
          u'enhanced-slides-enabled': 1, u'error-webservice-version': 1, u'monetization-models': 40,
          u'show-qr-button': 44, u'hide-info-tag': 1, u'timespan-webservice-version': 1,
          u'loyalty-rewards.sign-up-phone-screen-headline': 34, u'disable-order': 54,
          u'should-use-dummy-payment-manager': 108, u'payment-reversal-attempts': 42,
          u'loyalty-rewards.loyalty-tandc-link2-text': 34, u'loyalty.opt-for-emails': 1,
          u'presto-pergame-charge.maximum-charge': 1, u'loyalty.sms-opt-out-text': 1,
          u'RLDASH.gift_card_payment_module': 65, u'loyalty-rewards.loyalty-no-rewards-text': 34,
          u'presto-branding.payment-complete-screen.enabled': 1, u'control-panel.password': 64,
          u'survey.question-op2': 1, u'RLDASH.dash_user': 65, u'server-mode.send-order-alert-timeout-secs': 47,
          u'survey.star-label1': 1, u'mask-server-id.enabled': 1, u'survey.star-label3': 1,
          u'loyalty-rewards.loyalty-signup-year-enabled': 34, u'payment.pay-partial-label': 1,
          u'server-mode.handheld-lock-screen-login-aloha': 47, u'server-mode.order-modes.option-0.transmission-key': 47,
          u'payment-is-test-gateway-server': 106, u'survey.default-star-label5': 1,
          u'slideshow-brightness-percentage': 31, u'survey.star-label2': 1, u'back-office.retry-interval': 42,
          u'loyalty-rewards.sign-up-phone-screen-description': 34, u'test': 1, u'logging-configs.logging-levels': 1,
          u'show-cash-button': 1, u'payment-use-armor-token': 38,
          u'loyalty-rewards.slide-dismiss-loyalty-popup-prompt-timeout': 34,
          u'presto-credits.credit-to-dollar-exchange-rate': 1, u'survey.star-label5': 1,
          u'loyalty-rewards.loyalty-images-path': 34, u'no-receipt-option-enabled': 1,
          u'loyalty-rewards.loyalty-opt-tandc-screen-fields.loyalty-opt-tandc-screen-fields-link1-text': 34,
          u'block-system-home': 1, u'alert-trigger.order-sent': 39, u'loyalty-rewards.loyalty-banner-enabled': 34,
          u'loyalty-rewards.phone-number-validation-text': 34,
          u'loyalty-rewards.dismiss-loyalty-popup-prompt-from-prestoapp-bill-screen': 34, u'game-ratings-enabled': 1,
          u'home-nav.button-show-label-3': 54, u'home-nav.button-show-label-2': 51, u'debugging.webservice-api': 1,
          u'resource-sync.proxy-enabled': 83, u'survey.default-star-label2': 1,
          u'payment.print-receipt-option-enabled': 33, u'back-office.retry-on-error': 1, u'permanent-demo-mode': 108,
          u'survey.star-label4': 1, u'loyalty.signup-bill-screen-enabled': 34, u'payment-should-rollback-payment': 1,
          u'back-office.send-transaction-id': 1, u'server-mode.custom-memo-items-enabled': 80,
          u'show-payment-methods': 1, u'debugging.fake-menu-update.enabled': 1, u'touch-metrics-host': 1,
          u'loyalty.enabled': 1, u'payment-nfc-enabled': 72, u'custom-req-enabled': 76,
          u'kiosk.control-panel-access': 47, u'reorder.prompt-timeout': 1, u'local-log-enabled': 1,
          u'presto-credits.dialog-header-text-middle': 1, u'payment.check-tax-label': 1}
count = 0
new_dict = {}
for k, v in dict_1.items():
    main_sec = k.split('.')[0]
    new_dict[]

    # sub_sec = k.split('.')[1]
    # new_dict[main_sec] = sub_sec


# with open('app_other_yaml.txt', 'w') as f:
#     doc = yaml.dump(dict_1, f)
